name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go: [ '1.19', '1.20' ]
        
    name: Go ${{ matrix.go }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
        
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.51.2

    - name: Test
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      
    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./coverage.txt
